name: fo-prover
version: 0.0.1
github: rzetelskik/fo-prover
maintainer: Kacper Rzetelski <rzetelski.k@gmail.com>

ghc-options: -Wall

language: Haskell2010
default-extensions:
- UnicodeSyntax
- TypeSynonymInstances
- FlexibleInstances
- LambdaCase

dependencies:
- base >= 4.13 && < 5
- QuickCheck >= 2.14 && < 2.15
- parsec >= 3.1 && < 3.2
- mtl >= 2.2 && < 2.3
- random >= 1.2 && < 1.3
- containers >= 0.6 && < 0.7
- unordered-containers >= 0.2

executables:
  FO-prover:
    main: Main.hs
    source-dirs:
    - app
    - src
